# Generated by Django 6.0.2 on 2026-02-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comisiones", "0002_perfil"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfil",
            name="marca",
        ),
        migrations.RemoveField(
            model_name="perfil",
            name="modelo",
        ),
        migrations.AddField(
            model_name="perfil",
            name="foto_perfil",
            field=models.ImageField(blank=True, null=True, upload_to="perfiles/"),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="sede",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
