# Generated by Django 6.0.2 on 2026-02-10 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comisiones", "0005_incidencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidencia",
            name="fecha_incidencia",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
