# Generated by Django 6.0.2 on 2026-02-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0008_comision_comision_financiera_comision_facturacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ha_visto_perfil_inicial',
            field=models.BooleanField(default=False),
        ),
    ]
