# Generated by Django 6.0.2 on 2026-02-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comisiones", "0009_perfil_ha_visto_perfil_inicial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="area",
            field=models.CharField(
                choices=[
                    ("ventas", "Area de Ventas"),
                    ("postventa", "Area de Postventa"),
                ],
                default="ventas",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="perfil",
            name="concesionario",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="perfil",
            name="direccion_comercial",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="perfil",
            name="direccion_postventa",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="perfil",
            name="gerencia_nombre",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="perfil",
            name="jefatura_postventa",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="perfil",
            name="jefatura_ventas_nombre",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="perfil",
            name="responsable_postventa",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="perfil",
            name="responsable_vo",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
