# Generated by Django 6.0.2 on 2026-02-25 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comisiones", "0010_perfil_area_perfil_concesionario_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfil",
            name="concesionario",
        ),
        migrations.RemoveField(
            model_name="perfil",
            name="direccion_comercial",
        ),
        migrations.RemoveField(
            model_name="perfil",
            name="direccion_postventa",
        ),
        migrations.RemoveField(
            model_name="perfil",
            name="gerencia_nombre",
        ),
        migrations.RemoveField(
            model_name="perfil",
            name="jefatura_postventa",
        ),
        migrations.RemoveField(
            model_name="perfil",
            name="jefatura_ventas_nombre",
        ),
        migrations.RemoveField(
            model_name="perfil",
            name="responsable_postventa",
        ),
        migrations.RemoveField(
            model_name="perfil",
            name="responsable_vo",
        ),
    ]
