# Generated by Django 6.0.2 on 2026-02-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comisiones", "0011_remove_perfil_concesionario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="dni",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
