# Generated by Django 6.0.2 on 2026-02-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comisiones", "0012_perfil_dni"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="telefono",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
