# Generated by Django 6.0.2 on 2026-02-25 14:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comisiones", "0013_perfil_telefono"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Boletin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("boletin", models.CharField(max_length=200)),
                ("fecha", models.DateField(default=datetime.date.today)),
                ("marca", models.CharField(blank=True, default="", max_length=100)),
                ("tipo", models.CharField(blank=True, default="", max_length=100)),
                (
                    "archivo",
                    models.FileField(blank=True, null=True, upload_to="boletines/"),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LecturaBoletin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leido_en", models.DateTimeField(auto_now_add=True)),
                ("confirmado", models.BooleanField(default=True)),
                (
                    "boletin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecturas",
                        to="comisiones.boletin",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecturas_boletin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-leido_en"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("boletin", "usuario"),
                        name="uniq_lectura_boletin_usuario",
                    )
                ],
            },
        ),
    ]
