# Generated by Django 6.0.2 on 2026-02-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comisiones", "0014_boletin_lecturaboletin"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="concesionario",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
